import { describe, it, expect } from 'vitest';
import { generateProvisionSnippet } from '@/lib/provisions';

describe('generateProvisionSnippet', () => {
    const header = '# Generated by Avika Provisioner\n';

    describe('rate-limiting template', () => {
        it('should generate rate limiting config with default values', () => {
            const result = generateProvisionSnippet('rate-limiting', {});
            expect(result).toContain(header);
            expect(result).toContain('limit_req_zone');
            expect(result).toContain('rate=60r/m');
            expect(result).toContain('burst=20');
        });

        it('should generate rate limiting config with custom values', () => {
            const result = generateProvisionSnippet('rate-limiting', {
                requests_per_minute: 120,
                burst_size: 50,
            });
            expect(result).toContain('rate=120r/m');
            expect(result).toContain('burst=50');
        });

        it('should include location and proxy_pass directives', () => {
            const result = generateProvisionSnippet('rate-limiting', {});
            expect(result).toContain('location /api/');
            expect(result).toContain('proxy_pass http://backend');
        });
    });

    describe('health-checks template', () => {
        it('should generate health check config with default values', () => {
            const result = generateProvisionSnippet('health-checks', {});
            expect(result).toContain(header);
            expect(result).toContain('upstream backend');
            expect(result).toContain('interval=3000');
            expect(result).toContain('rise=2');
            expect(result).toContain('fall=3');
            expect(result).toContain('timeout=1000');
        });

        it('should generate health check config with custom upstream name', () => {
            const result = generateProvisionSnippet('health-checks', {
                upstream_name: 'api_servers',
            });
            expect(result).toContain('upstream api_servers');
        });

        it('should use custom servers when provided', () => {
            const result = generateProvisionSnippet('health-checks', {
                servers: '    server 10.0.0.1:8080;\n    server 10.0.0.2:8080;',
            });
            expect(result).toContain('server 10.0.0.1:8080');
            expect(result).toContain('server 10.0.0.2:8080');
        });

        it('should use custom check interval', () => {
            const result = generateProvisionSnippet('health-checks', {
                interval: 5000,
                rise: 3,
                fall: 5,
                timeout: 2000,
            });
            expect(result).toContain('interval=5000');
            expect(result).toContain('rise=3');
            expect(result).toContain('fall=5');
            expect(result).toContain('timeout=2000');
        });
    });

    describe('location-blocks template', () => {
        it('should generate location block with default values', () => {
            const result = generateProvisionSnippet('location-blocks', {});
            expect(result).toContain(header);
            expect(result).toContain('location /');
            expect(result).toContain('# Add directives here');
        });

        it('should generate location block with custom path', () => {
            const result = generateProvisionSnippet('location-blocks', {
                path: '/api/v2',
                directives: '    proxy_pass http://api_v2;',
            });
            expect(result).toContain('location /api/v2');
            expect(result).toContain('proxy_pass http://api_v2');
        });
    });

    describe('error-pages template', () => {
        it('should generate error pages config with default values', () => {
            const result = generateProvisionSnippet('error-pages', {});
            expect(result).toContain(header);
            expect(result).toContain('error_page 404 500 502 /error.html');
            expect(result).toContain('location = /error.html');
            expect(result).toContain('root /usr/share/nginx/html');
            expect(result).toContain('internal');
        });

        it('should generate error pages config with custom values', () => {
            const result = generateProvisionSnippet('error-pages', {
                error_codes: '500 502 503 504',
                page_path: '/50x.html',
            });
            expect(result).toContain('error_page 500 502 503 504 /50x.html');
            expect(result).toContain('location = /50x.html');
        });
    });

    describe('custom template', () => {
        it('should generate custom config with raw_config', () => {
            const customConfig = 'worker_processes auto;\nevents { worker_connections 1024; }';
            const result = generateProvisionSnippet('custom', {
                raw_config: customConfig,
            });
            expect(result).toContain(header);
            expect(result).toContain(customConfig);
        });

        it('should generate comment when no raw_config provided', () => {
            const result = generateProvisionSnippet('custom', {});
            expect(result).toContain(header);
            expect(result).toContain('# No config provided');
        });
    });

    describe('unknown template', () => {
        it('should return unknown template message', () => {
            const result = generateProvisionSnippet('nonexistent', {});
            expect(result).toBe('# Unknown template');
        });
    });

    describe('header inclusion', () => {
        const templates = ['rate-limiting', 'health-checks', 'location-blocks', 'error-pages', 'custom'];
        templates.forEach((template) => {
            it(`should include header in ${template} template`, () => {
                const result = generateProvisionSnippet(template, {});
                expect(result.startsWith(header)).toBe(true);
            });
        });
    });
});
