// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Commander_Connect_FullMethodName = "/nginx.agent.v1.Commander/Connect"
)

// CommanderClient is the client API for Commander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommanderClient interface {
	// Bi-directional stream:
	// - Agent sends Heartbeats, CommandAck, StateChanges
	// - Server sends ConfigPush, RestartCmd, SamplingPolicy
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerCommand], error)
}

type commanderClient struct {
	cc grpc.ClientConnInterface
}

func NewCommanderClient(cc grpc.ClientConnInterface) CommanderClient {
	return &commanderClient{cc}
}

func (c *commanderClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Commander_ServiceDesc.Streams[0], Commander_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Commander_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ServerCommand]

// CommanderServer is the server API for Commander service.
// All implementations must embed UnimplementedCommanderServer
// for forward compatibility.
type CommanderServer interface {
	// Bi-directional stream:
	// - Agent sends Heartbeats, CommandAck, StateChanges
	// - Server sends ConfigPush, RestartCmd, SamplingPolicy
	Connect(grpc.BidiStreamingServer[AgentMessage, ServerCommand]) error
	mustEmbedUnimplementedCommanderServer()
}

// UnimplementedCommanderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommanderServer struct{}

func (UnimplementedCommanderServer) Connect(grpc.BidiStreamingServer[AgentMessage, ServerCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedCommanderServer) mustEmbedUnimplementedCommanderServer() {}
func (UnimplementedCommanderServer) testEmbeddedByValue()                   {}

// UnsafeCommanderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommanderServer will
// result in compilation errors.
type UnsafeCommanderServer interface {
	mustEmbedUnimplementedCommanderServer()
}

func RegisterCommanderServer(s grpc.ServiceRegistrar, srv CommanderServer) {
	// If the following call panics, it indicates UnimplementedCommanderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Commander_ServiceDesc, srv)
}

func _Commander_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommanderServer).Connect(&grpc.GenericServerStream[AgentMessage, ServerCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Commander_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ServerCommand]

// Commander_ServiceDesc is the grpc.ServiceDesc for Commander service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Commander_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nginx.agent.v1.Commander",
	HandlerType: (*CommanderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Commander_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}

const (
	AgentService_GetConfig_FullMethodName          = "/nginx.agent.v1.AgentService/GetConfig"
	AgentService_UpdateConfig_FullMethodName       = "/nginx.agent.v1.AgentService/UpdateConfig"
	AgentService_ValidateConfig_FullMethodName     = "/nginx.agent.v1.AgentService/ValidateConfig"
	AgentService_ReloadNginx_FullMethodName        = "/nginx.agent.v1.AgentService/ReloadNginx"
	AgentService_RestartNginx_FullMethodName       = "/nginx.agent.v1.AgentService/RestartNginx"
	AgentService_StopNginx_FullMethodName          = "/nginx.agent.v1.AgentService/StopNginx"
	AgentService_ListCertificates_FullMethodName   = "/nginx.agent.v1.AgentService/ListCertificates"
	AgentService_GetLogs_FullMethodName            = "/nginx.agent.v1.AgentService/GetLogs"
	AgentService_ListAgents_FullMethodName         = "/nginx.agent.v1.AgentService/ListAgents"
	AgentService_GetAgent_FullMethodName           = "/nginx.agent.v1.AgentService/GetAgent"
	AgentService_RemoveAgent_FullMethodName        = "/nginx.agent.v1.AgentService/RemoveAgent"
	AgentService_GetUptimeReports_FullMethodName   = "/nginx.agent.v1.AgentService/GetUptimeReports"
	AgentService_GetAnalytics_FullMethodName       = "/nginx.agent.v1.AgentService/GetAnalytics"
	AgentService_StreamAnalytics_FullMethodName    = "/nginx.agent.v1.AgentService/StreamAnalytics"
	AgentService_GetTraces_FullMethodName          = "/nginx.agent.v1.AgentService/GetTraces"
	AgentService_GetTraceDetails_FullMethodName    = "/nginx.agent.v1.AgentService/GetTraceDetails"
	AgentService_GetRecommendations_FullMethodName = "/nginx.agent.v1.AgentService/GetRecommendations"
	AgentService_ApplyAugment_FullMethodName       = "/nginx.agent.v1.AgentService/ApplyAugment"
	AgentService_UpdateAgent_FullMethodName        = "/nginx.agent.v1.AgentService/UpdateAgent"
	AgentService_Execute_FullMethodName            = "/nginx.agent.v1.AgentService/Execute"
	AgentService_GetAgentConfig_FullMethodName     = "/nginx.agent.v1.AgentService/GetAgentConfig"
	AgentService_UpdateAgentConfig_FullMethodName  = "/nginx.agent.v1.AgentService/UpdateAgentConfig"
	AgentService_GenerateReport_FullMethodName     = "/nginx.agent.v1.AgentService/GenerateReport"
	AgentService_SendReport_FullMethodName         = "/nginx.agent.v1.AgentService/SendReport"
	AgentService_DownloadReport_FullMethodName     = "/nginx.agent.v1.AgentService/DownloadReport"
	AgentService_ListAlertRules_FullMethodName     = "/nginx.agent.v1.AgentService/ListAlertRules"
	AgentService_CreateAlertRule_FullMethodName    = "/nginx.agent.v1.AgentService/CreateAlertRule"
	AgentService_DeleteAlertRule_FullMethodName    = "/nginx.agent.v1.AgentService/DeleteAlertRule"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// Configuration Management
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*ConfigUpdateResponse, error)
	ValidateConfig(ctx context.Context, in *ConfigValidation, opts ...grpc.CallOption) (*ValidationResult, error)
	ReloadNginx(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	RestartNginx(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
	StopNginx(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
	// Certificate Management
	ListCertificates(ctx context.Context, in *CertListRequest, opts ...grpc.CallOption) (*CertListResponse, error)
	// Log Management
	GetLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// List currently connected agents
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// Get a single agent's info
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error)
	// Remove an agent from inventory
	RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error)
	// Uptime & Monitoring
	GetUptimeReports(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error)
	// Analytics
	GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
	// Stream Analytics for real-time dashboards
	StreamAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyticsResponse], error)
	// Tracing
	GetTraces(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceList, error)
	GetTraceDetails(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*Trace, error)
	// AI Tuner
	GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error)
	// Config Augments (Provisions)
	ApplyAugment(ctx context.Context, in *ApplyAugmentRequest, opts ...grpc.CallOption) (*ApplyAugmentResponse, error)
	// Agent Management
	UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error)
	// Command Execution (Shell)
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error)
	// Agent Configuration
	GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error)
	UpdateAgentConfig(ctx context.Context, in *AgentConfig, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	// Reporting
	GenerateReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
	SendReport(ctx context.Context, in *SendReportRequest, opts ...grpc.CallOption) (*SendReportResponse, error)
	DownloadReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportDownloadResponse, error)
	// Alerting
	ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*AlertRuleList, error)
	CreateAlertRule(ctx context.Context, in *AlertRule, opts ...grpc.CallOption) (*AlertRule, error)
	DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateConfig(ctx context.Context, in *ConfigUpdate, opts ...grpc.CallOption) (*ConfigUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigUpdateResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ValidateConfig(ctx context.Context, in *ConfigValidation, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, AgentService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReloadNginx(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, AgentService_ReloadNginx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RestartNginx(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, AgentService_RestartNginx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StopNginx(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, AgentService_StopNginx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListCertificates(ctx context.Context, in *CertListRequest, opts ...grpc.CallOption) (*CertListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertListResponse)
	err := c.cc.Invoke(ctx, AgentService_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_GetLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *agentServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfo)
	err := c.cc.Invoke(ctx, AgentService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_RemoveAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetUptimeReports(ctx context.Context, in *UptimeRequest, opts ...grpc.CallOption) (*UptimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUptimeReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StreamAnalytics(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnalyticsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_StreamAnalytics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnalyticsRequest, AnalyticsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamAnalyticsClient = grpc.ServerStreamingClient[AnalyticsResponse]

func (c *agentServiceClient) GetTraces(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceList)
	err := c.cc.Invoke(ctx, AgentService_GetTraces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetTraceDetails(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*Trace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Trace)
	err := c.cc.Invoke(ctx, AgentService_GetTraceDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetRecommendations(ctx context.Context, in *RecommendationRequest, opts ...grpc.CallOption) (*RecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationResponse)
	err := c.cc.Invoke(ctx, AgentService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ApplyAugment(ctx context.Context, in *ApplyAugmentRequest, opts ...grpc.CallOption) (*ApplyAugmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyAugmentResponse)
	err := c.cc.Invoke(ctx, AgentService_ApplyAugment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgent(ctx context.Context, in *UpdateAgentRequest, opts ...grpc.CallOption) (*UpdateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecRequest, ExecResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteClient = grpc.BidiStreamingClient[ExecRequest, ExecResponse]

func (c *agentServiceClient) GetAgentConfig(ctx context.Context, in *GetAgentConfigRequest, opts ...grpc.CallOption) (*AgentConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfig)
	err := c.cc.Invoke(ctx, AgentService_GetAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateAgentConfig(ctx context.Context, in *AgentConfig, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, AgentService_GenerateReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendReport(ctx context.Context, in *SendReportRequest, opts ...grpc.CallOption) (*SendReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReportResponse)
	err := c.cc.Invoke(ctx, AgentService_SendReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DownloadReport(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportDownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportDownloadResponse)
	err := c.cc.Invoke(ctx, AgentService_DownloadReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListAlertRules(ctx context.Context, in *ListAlertRulesRequest, opts ...grpc.CallOption) (*AlertRuleList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRuleList)
	err := c.cc.Invoke(ctx, AgentService_ListAlertRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CreateAlertRule(ctx context.Context, in *AlertRule, opts ...grpc.CallOption) (*AlertRule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlertRule)
	err := c.cc.Invoke(ctx, AgentService_CreateAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteAlertRule(ctx context.Context, in *DeleteAlertRuleRequest, opts ...grpc.CallOption) (*DeleteAlertRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAlertRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteAlertRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	// Configuration Management
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	UpdateConfig(context.Context, *ConfigUpdate) (*ConfigUpdateResponse, error)
	ValidateConfig(context.Context, *ConfigValidation) (*ValidationResult, error)
	ReloadNginx(context.Context, *ReloadRequest) (*ReloadResponse, error)
	RestartNginx(context.Context, *RestartRequest) (*RestartResponse, error)
	StopNginx(context.Context, *StopRequest) (*StopResponse, error)
	// Certificate Management
	ListCertificates(context.Context, *CertListRequest) (*CertListResponse, error)
	// Log Management
	GetLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error
	// List currently connected agents
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// Get a single agent's info
	GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error)
	// Remove an agent from inventory
	RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error)
	// Uptime & Monitoring
	GetUptimeReports(context.Context, *UptimeRequest) (*UptimeResponse, error)
	// Analytics
	GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error)
	// Stream Analytics for real-time dashboards
	StreamAnalytics(*AnalyticsRequest, grpc.ServerStreamingServer[AnalyticsResponse]) error
	// Tracing
	GetTraces(context.Context, *TraceRequest) (*TraceList, error)
	GetTraceDetails(context.Context, *TraceRequest) (*Trace, error)
	// AI Tuner
	GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error)
	// Config Augments (Provisions)
	ApplyAugment(context.Context, *ApplyAugmentRequest) (*ApplyAugmentResponse, error)
	// Agent Management
	UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error)
	// Command Execution (Shell)
	Execute(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error
	// Agent Configuration
	GetAgentConfig(context.Context, *GetAgentConfigRequest) (*AgentConfig, error)
	UpdateAgentConfig(context.Context, *AgentConfig) (*AgentConfigResponse, error)
	// Reporting
	GenerateReport(context.Context, *ReportRequest) (*ReportResponse, error)
	SendReport(context.Context, *SendReportRequest) (*SendReportResponse, error)
	DownloadReport(context.Context, *ReportRequest) (*ReportDownloadResponse, error)
	// Alerting
	ListAlertRules(context.Context, *ListAlertRulesRequest) (*AlertRuleList, error)
	CreateAlertRule(context.Context, *AlertRule) (*AlertRule, error)
	DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAgentServiceServer) UpdateConfig(context.Context, *ConfigUpdate) (*ConfigUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAgentServiceServer) ValidateConfig(context.Context, *ConfigValidation) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedAgentServiceServer) ReloadNginx(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadNginx not implemented")
}
func (UnimplementedAgentServiceServer) RestartNginx(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartNginx not implemented")
}
func (UnimplementedAgentServiceServer) StopNginx(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopNginx not implemented")
}
func (UnimplementedAgentServiceServer) ListCertificates(context.Context, *CertListRequest) (*CertListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedAgentServiceServer) GetLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedAgentServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentServiceServer) GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentServiceServer) RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAgent not implemented")
}
func (UnimplementedAgentServiceServer) GetUptimeReports(context.Context, *UptimeRequest) (*UptimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUptimeReports not implemented")
}
func (UnimplementedAgentServiceServer) GetAnalytics(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalytics not implemented")
}
func (UnimplementedAgentServiceServer) StreamAnalytics(*AnalyticsRequest, grpc.ServerStreamingServer[AnalyticsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamAnalytics not implemented")
}
func (UnimplementedAgentServiceServer) GetTraces(context.Context, *TraceRequest) (*TraceList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraces not implemented")
}
func (UnimplementedAgentServiceServer) GetTraceDetails(context.Context, *TraceRequest) (*Trace, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceDetails not implemented")
}
func (UnimplementedAgentServiceServer) GetRecommendations(context.Context, *RecommendationRequest) (*RecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedAgentServiceServer) ApplyAugment(context.Context, *ApplyAugmentRequest) (*ApplyAugmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyAugment not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgent(context.Context, *UpdateAgentRequest) (*UpdateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgent not implemented")
}
func (UnimplementedAgentServiceServer) Execute(grpc.BidiStreamingServer[ExecRequest, ExecResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAgentServiceServer) GetAgentConfig(context.Context, *GetAgentConfigRequest) (*AgentConfig, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentConfig not implemented")
}
func (UnimplementedAgentServiceServer) UpdateAgentConfig(context.Context, *AgentConfig) (*AgentConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentConfig not implemented")
}
func (UnimplementedAgentServiceServer) GenerateReport(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateReport not implemented")
}
func (UnimplementedAgentServiceServer) SendReport(context.Context, *SendReportRequest) (*SendReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReport not implemented")
}
func (UnimplementedAgentServiceServer) DownloadReport(context.Context, *ReportRequest) (*ReportDownloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadReport not implemented")
}
func (UnimplementedAgentServiceServer) ListAlertRules(context.Context, *ListAlertRulesRequest) (*AlertRuleList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlertRules not implemented")
}
func (UnimplementedAgentServiceServer) CreateAlertRule(context.Context, *AlertRule) (*AlertRule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlertRule not implemented")
}
func (UnimplementedAgentServiceServer) DeleteAlertRule(context.Context, *DeleteAlertRuleRequest) (*DeleteAlertRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAlertRule not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateConfig(ctx, req.(*ConfigUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigValidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ValidateConfig(ctx, req.(*ConfigValidation))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReloadNginx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReloadNginx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReloadNginx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReloadNginx(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RestartNginx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RestartNginx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RestartNginx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RestartNginx(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StopNginx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).StopNginx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_StopNginx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).StopNginx(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListCertificates(ctx, req.(*CertListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).GetLogs(m, &grpc.GenericServerStream[LogRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_GetLogsServer = grpc.ServerStreamingServer[LogEntry]

func _AgentService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RemoveAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RemoveAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RemoveAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RemoveAgent(ctx, req.(*RemoveAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetUptimeReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UptimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUptimeReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUptimeReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUptimeReports(ctx, req.(*UptimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAnalytics(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StreamAnalytics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnalyticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamAnalytics(m, &grpc.GenericServerStream[AnalyticsRequest, AnalyticsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamAnalyticsServer = grpc.ServerStreamingServer[AnalyticsResponse]

func _AgentService_GetTraces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTraces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTraces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTraces(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetTraceDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetTraceDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetTraceDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetTraceDetails(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetRecommendations(ctx, req.(*RecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ApplyAugment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyAugmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ApplyAugment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ApplyAugment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ApplyAugment(ctx, req.(*ApplyAugmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgent(ctx, req.(*UpdateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Execute(&grpc.GenericServerStream[ExecRequest, ExecResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteServer = grpc.BidiStreamingServer[ExecRequest, ExecResponse]

func _AgentService_GetAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetAgentConfig(ctx, req.(*GetAgentConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateAgentConfig(ctx, req.(*AgentConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendReport(ctx, req.(*SendReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DownloadReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DownloadReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DownloadReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DownloadReport(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListAlertRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListAlertRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListAlertRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListAlertRules(ctx, req.(*ListAlertRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CreateAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlertRule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CreateAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CreateAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CreateAlertRule(ctx, req.(*AlertRule))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteAlertRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAlertRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteAlertRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteAlertRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteAlertRule(ctx, req.(*DeleteAlertRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nginx.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _AgentService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AgentService_UpdateConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _AgentService_ValidateConfig_Handler,
		},
		{
			MethodName: "ReloadNginx",
			Handler:    _AgentService_ReloadNginx_Handler,
		},
		{
			MethodName: "RestartNginx",
			Handler:    _AgentService_RestartNginx_Handler,
		},
		{
			MethodName: "StopNginx",
			Handler:    _AgentService_StopNginx_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _AgentService_ListCertificates_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentService_GetAgent_Handler,
		},
		{
			MethodName: "RemoveAgent",
			Handler:    _AgentService_RemoveAgent_Handler,
		},
		{
			MethodName: "GetUptimeReports",
			Handler:    _AgentService_GetUptimeReports_Handler,
		},
		{
			MethodName: "GetAnalytics",
			Handler:    _AgentService_GetAnalytics_Handler,
		},
		{
			MethodName: "GetTraces",
			Handler:    _AgentService_GetTraces_Handler,
		},
		{
			MethodName: "GetTraceDetails",
			Handler:    _AgentService_GetTraceDetails_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _AgentService_GetRecommendations_Handler,
		},
		{
			MethodName: "ApplyAugment",
			Handler:    _AgentService_ApplyAugment_Handler,
		},
		{
			MethodName: "UpdateAgent",
			Handler:    _AgentService_UpdateAgent_Handler,
		},
		{
			MethodName: "GetAgentConfig",
			Handler:    _AgentService_GetAgentConfig_Handler,
		},
		{
			MethodName: "UpdateAgentConfig",
			Handler:    _AgentService_UpdateAgentConfig_Handler,
		},
		{
			MethodName: "GenerateReport",
			Handler:    _AgentService_GenerateReport_Handler,
		},
		{
			MethodName: "SendReport",
			Handler:    _AgentService_SendReport_Handler,
		},
		{
			MethodName: "DownloadReport",
			Handler:    _AgentService_DownloadReport_Handler,
		},
		{
			MethodName: "ListAlertRules",
			Handler:    _AgentService_ListAlertRules_Handler,
		},
		{
			MethodName: "CreateAlertRule",
			Handler:    _AgentService_CreateAlertRule_Handler,
		},
		{
			MethodName: "DeleteAlertRule",
			Handler:    _AgentService_DeleteAlertRule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _AgentService_GetLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAnalytics",
			Handler:       _AgentService_StreamAnalytics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _AgentService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
