---
# Source: nginx-manager/templates/frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nginx-manager-frontend
  labels:
    helm.sh/chart: nginx-manager-0.1.0
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: release-name
    component: frontend
---
# Source: nginx-manager/templates/frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-nginx-manager-frontend
  labels:
    helm.sh/chart: nginx-manager-0.1.0
    app.kubernetes.io/name: nginx-manager
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-manager
      app.kubernetes.io/instance: release-name
      component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-manager
        app.kubernetes.io/instance: release-name
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "frontend:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: GATEWAY_URL
              value: "release-name-nginx-manager-gateway:50051"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
