---
# Source: nginx-manager/templates/redpanda.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-redpanda
spec:
  ports:
    - port: 9092
  selector:
    app: redpanda
---
# Source: nginx-manager/templates/redpanda.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-redpanda
spec:
  serviceName: release-name-redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.3
          args:
            - redpanda
            - start
            - --kafka-addr PLAIN://0.0.0.0:9092
            - --advertise-kafka-addr release-name-redpanda:9092
            - --check=false
          ports:
            - containerPort: 9092
