#!/usr/bin/env bash
#
# Interactive helper: local HTTPS for Next.js + env snippet for gateway/gRPC TLS and optional DB/ClickHouse.
# Does not start services. Writes frontend/.env.local.https-snippet (merge into .env.local manually).
#
# Usage: ./scripts/dev-https-local.sh
# From repo root (recommended).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

SNIPPET="$ROOT/frontend/.env.local.https-snippet"
CERT_DIR="$ROOT/certs/local"

say() { printf '%s\n' "$*"; }

prompt() {
  local __def="$2"
  local __v
  read -r -p "$1 [${__def}]: " __v || true
  if [[ -z "${__v}" ]]; then
    __v="$__def"
  fi
  printf '%s' "$__v"
}

prompt_yn() {
  local __def="$2"
  local __v
  read -r -p "$1 (y/N) [${__def}]: " __v || true
  __v="$(printf '%s' "$__v" | tr '[:upper:]' '[:lower:]')"
  if [[ -z "$__v" ]]; then
    __v="$__def"
  fi
  [[ "$__v" == "y" || "$__v" == "yes" ]]
}

say "== Avika — local HTTPS / env snippet =="
say "Repo: $ROOT"
say ""

GW_HTTP="$(prompt "Gateway HTTP base URL (REST)" "http://localhost:5021")"
GW_GRPC="$(prompt "Gateway gRPC host:port (no scheme)" "localhost:5020")"
GW_EXT="$(prompt "GATEWAY_EXTERNAL_URL for browser WS (optional, blank to skip)" "")"
BASE_PATH="$(prompt "NEXT_PUBLIC_BASE_PATH (e.g. /avika or empty)" "")"

say ""
say "--- gRPC from Next to gateway (BFF) ---"
if prompt_yn "Enable TLS on gRPC client (ENABLE_TLS)?" "n"; then
  GRPC_TLS="true"
  CA_FILE="$(prompt "Path to TLS_CA_CERT_FILE (PEM, optional for public CAs)" "")"
  if prompt_yn "Use mTLS (client cert + key on Next)?" "n"; then
    CLI_CERT="$(prompt "TLS_CLIENT_CERT_FILE path" "$CERT_DIR/next-grpc-client.pem")"
    CLI_KEY="$(prompt "TLS_CLIENT_KEY_FILE path" "$CERT_DIR/next-grpc-client-key.pem")"
  else
    CLI_CERT=""
    CLI_KEY=""
  fi
else
  GRPC_TLS="false"
  CA_FILE=""
  CLI_CERT=""
  CLI_KEY=""
fi

say ""
say "--- Optional: gateway-oriented vars (reference only; gateway reads its own env) ---"
if prompt_yn "Include DB_DSN line in snippet?" "n"; then
  DB_DSN="$(prompt "DB_DSN (Postgres)" "postgres://user:pass@localhost:5432/avika?sslmode=disable")"
else
  DB_DSN=""
fi

if prompt_yn "Include CLICKHOUSE_* placeholders in snippet?" "n"; then
  CH_ADDR="$(prompt "CLICKHOUSE_ADDR" "localhost:9000")"
  CH_DB="$(prompt "CLICKHOUSE_DATABASE" "default")"
  CH_USER="$(prompt "CLICKHOUSE_USER" "default")"
  CH_PASS="$(prompt "CLICKHOUSE_PASSWORD" "***")"
else
  CH_ADDR=""
fi

say ""
say "--- Next.js dev HTTPS certificates ---"
mkdir -p "$CERT_DIR"
NEXT_KEY="$CERT_DIR/next-dev-key.pem"
NEXT_CERT="$CERT_DIR/next-dev.pem"

if prompt_yn "Generate TLS cert/key for next dev (recommended if you do not have files yet)?" "y"; then
  if command -v mkcert >/dev/null 2>&1; then
    say "Using mkcert..."
    mkcert -key-file "$NEXT_KEY" -cert-file "$NEXT_CERT" localhost 127.0.0.1 ::1
  else
    say "mkcert not found; generating self-signed cert with openssl (browser will warn once)."
    openssl req -x509 -newkey rsa:2048 \
      -keyout "$NEXT_KEY" \
      -out "$NEXT_CERT" \
      -days 365 -nodes \
      -subj "/CN=localhost" \
      2>/dev/null
  fi
else
  NEXT_KEY="$(prompt "Path to existing key PEM" "$NEXT_KEY")"
  NEXT_CERT="$(prompt "Path to existing cert PEM" "$NEXT_CERT")"
fi

say ""
say "--- Writing snippet: $SNIPPET ---"

{
  say "# Generated by scripts/dev-https-local.sh — merge into frontend/.env.local"
  say "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  say ""
  say "GATEWAY_HTTP_URL=$GW_HTTP"
  say "GATEWAY_GRPC_ADDR=$GW_GRPC"
  if [[ -n "$GW_EXT" ]]; then
    say "GATEWAY_EXTERNAL_URL=$GW_EXT"
  fi
  if [[ -n "$BASE_PATH" ]]; then
    say "NEXT_PUBLIC_BASE_PATH=$BASE_PATH"
  fi
  say "ENABLE_TLS=$GRPC_TLS"
  say "GATEWAY_TLS=$GRPC_TLS"
  if [[ -n "$CA_FILE" ]]; then
    say "TLS_CA_CERT_FILE=$CA_FILE"
  fi
  if [[ -n "$CLI_CERT" && -n "$CLI_KEY" ]]; then
    say "TLS_CLIENT_CERT_FILE=$CLI_CERT"
    say "TLS_CLIENT_KEY_FILE=$CLI_KEY"
  fi
  if [[ -n "$DB_DSN" ]]; then
    say ""
    say "# Gateway process (not Next) — copy to gateway env if you run gateway locally:"
    say "# DB_DSN=$DB_DSN"
  fi
  if [[ -n "$CH_ADDR" ]]; then
    say "# CLICKHOUSE_ADDR=$CH_ADDR"
    say "# CLICKHOUSE_DATABASE=$CH_DB"
    say "# CLICKHOUSE_USER=$CH_USER"
    say "# CLICKHOUSE_PASSWORD=$CH_PASS"
  fi

  say ""
  say "# --- PSK (agents only; set on gateway + agent; not for UI login) ---"
  say "# PSK_ENABLED=true"
  say "# PSK_KEY=<hex from: openssl rand -hex 32>"
  say "# Agent: same key via PSK_KEY or -psk. See docs/QUICK_REFERENCE.md"
} >"$SNIPPET"

say "Wrote: $SNIPPET"
say ""
say "Next steps:"
say "  1. Review and merge snippet into frontend/.env.local"
say "  2. Start Next with HTTPS, for example:"
say "     cd frontend && npx next dev --experimental-https \\"
say "       --experimental-https-key $NEXT_KEY \\"
say "       --experimental-https-cert $NEXT_CERT"
say ""
say "Optional npm script (add to frontend/package.json dev:https):"
say '  "dev:https": "next dev --experimental-https --experimental-https-key ../certs/local/next-dev-key.pem --experimental-https-cert ../certs/local/next-dev.pem"'
say ""
say "Certs directory: $CERT_DIR (keep private; do not commit)"
