// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: agent_config.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentConfigService_GetAgentConfig_FullMethodName      = "/nginx.agent.v1.AgentConfigService/GetAgentConfig"
	AgentConfigService_UpdateAgentConfig_FullMethodName   = "/nginx.agent.v1.AgentConfigService/UpdateAgentConfig"
	AgentConfigService_TestConnection_FullMethodName      = "/nginx.agent.v1.AgentConfigService/TestConnection"
	AgentConfigService_ListConfigBackups_FullMethodName   = "/nginx.agent.v1.AgentConfigService/ListConfigBackups"
	AgentConfigService_RestoreConfigBackup_FullMethodName = "/nginx.agent.v1.AgentConfigService/RestoreConfigBackup"
)

// AgentConfigServiceClient is the client API for AgentConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Separate service for agent self-configuration.
// This service focuses on configuring the agent process itself (not NGINX config).
type AgentConfigServiceClient interface {
	GetAgentConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AgentConfigResponse, error)
	UpdateAgentConfig(ctx context.Context, in *AgentConfigUpdate, opts ...grpc.CallOption) (*AgentConfigUpdateResponse, error)
	TestConnection(ctx context.Context, in *ConnectionTestRequest, opts ...grpc.CallOption) (*ConnectionTestResponse, error)
	ListConfigBackups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConfigBackupsResponse, error)
	RestoreConfigBackup(ctx context.Context, in *RestoreConfigBackupRequest, opts ...grpc.CallOption) (*AgentConfigUpdateResponse, error)
}

type agentConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentConfigServiceClient(cc grpc.ClientConnInterface) AgentConfigServiceClient {
	return &agentConfigServiceClient{cc}
}

func (c *agentConfigServiceClient) GetAgentConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AgentConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_GetAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigServiceClient) UpdateAgentConfig(ctx context.Context, in *AgentConfigUpdate, opts ...grpc.CallOption) (*AgentConfigUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigUpdateResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_UpdateAgentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigServiceClient) TestConnection(ctx context.Context, in *ConnectionTestRequest, opts ...grpc.CallOption) (*ConnectionTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionTestResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_TestConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigServiceClient) ListConfigBackups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListConfigBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConfigBackupsResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_ListConfigBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentConfigServiceClient) RestoreConfigBackup(ctx context.Context, in *RestoreConfigBackupRequest, opts ...grpc.CallOption) (*AgentConfigUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentConfigUpdateResponse)
	err := c.cc.Invoke(ctx, AgentConfigService_RestoreConfigBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentConfigServiceServer is the server API for AgentConfigService service.
// All implementations must embed UnimplementedAgentConfigServiceServer
// for forward compatibility.
//
// Separate service for agent self-configuration.
// This service focuses on configuring the agent process itself (not NGINX config).
type AgentConfigServiceServer interface {
	GetAgentConfig(context.Context, *emptypb.Empty) (*AgentConfigResponse, error)
	UpdateAgentConfig(context.Context, *AgentConfigUpdate) (*AgentConfigUpdateResponse, error)
	TestConnection(context.Context, *ConnectionTestRequest) (*ConnectionTestResponse, error)
	ListConfigBackups(context.Context, *emptypb.Empty) (*ListConfigBackupsResponse, error)
	RestoreConfigBackup(context.Context, *RestoreConfigBackupRequest) (*AgentConfigUpdateResponse, error)
	mustEmbedUnimplementedAgentConfigServiceServer()
}

// UnimplementedAgentConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentConfigServiceServer struct{}

func (UnimplementedAgentConfigServiceServer) GetAgentConfig(context.Context, *emptypb.Empty) (*AgentConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentConfig not implemented")
}
func (UnimplementedAgentConfigServiceServer) UpdateAgentConfig(context.Context, *AgentConfigUpdate) (*AgentConfigUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAgentConfig not implemented")
}
func (UnimplementedAgentConfigServiceServer) TestConnection(context.Context, *ConnectionTestRequest) (*ConnectionTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestConnection not implemented")
}
func (UnimplementedAgentConfigServiceServer) ListConfigBackups(context.Context, *emptypb.Empty) (*ListConfigBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConfigBackups not implemented")
}
func (UnimplementedAgentConfigServiceServer) RestoreConfigBackup(context.Context, *RestoreConfigBackupRequest) (*AgentConfigUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreConfigBackup not implemented")
}
func (UnimplementedAgentConfigServiceServer) mustEmbedUnimplementedAgentConfigServiceServer() {}
func (UnimplementedAgentConfigServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentConfigServiceServer will
// result in compilation errors.
type UnsafeAgentConfigServiceServer interface {
	mustEmbedUnimplementedAgentConfigServiceServer()
}

func RegisterAgentConfigServiceServer(s grpc.ServiceRegistrar, srv AgentConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentConfigService_ServiceDesc, srv)
}

func _AgentConfigService_GetAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).GetAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_GetAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).GetAgentConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfigService_UpdateAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentConfigUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).UpdateAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_UpdateAgentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).UpdateAgentConfig(ctx, req.(*AgentConfigUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfigService_TestConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).TestConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_TestConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).TestConnection(ctx, req.(*ConnectionTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfigService_ListConfigBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).ListConfigBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_ListConfigBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).ListConfigBackups(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentConfigService_RestoreConfigBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreConfigBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentConfigServiceServer).RestoreConfigBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentConfigService_RestoreConfigBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentConfigServiceServer).RestoreConfigBackup(ctx, req.(*RestoreConfigBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentConfigService_ServiceDesc is the grpc.ServiceDesc for AgentConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nginx.agent.v1.AgentConfigService",
	HandlerType: (*AgentConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentConfig",
			Handler:    _AgentConfigService_GetAgentConfig_Handler,
		},
		{
			MethodName: "UpdateAgentConfig",
			Handler:    _AgentConfigService_UpdateAgentConfig_Handler,
		},
		{
			MethodName: "TestConnection",
			Handler:    _AgentConfigService_TestConnection_Handler,
		},
		{
			MethodName: "ListConfigBackups",
			Handler:    _AgentConfigService_ListConfigBackups_Handler,
		},
		{
			MethodName: "RestoreConfigBackup",
			Handler:    _AgentConfigService_RestoreConfigBackup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_config.proto",
}
