// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/agent_config.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GatewayAddress  string                 `protobuf:"bytes,1,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthPort      int32                  `protobuf:"varint,4,opt,name=health_port,json=healthPort,proto3" json:"health_port,omitempty"`
	MgmtPort        int32                  `protobuf:"varint,5,opt,name=mgmt_port,json=mgmtPort,proto3" json:"mgmt_port,omitempty"`
	NginxConfigPath string                 `protobuf:"bytes,6,opt,name=nginx_config_path,json=nginxConfigPath,proto3" json:"nginx_config_path,omitempty"`
	NginxStatusUrl  string                 `protobuf:"bytes,7,opt,name=nginx_status_url,json=nginxStatusUrl,proto3" json:"nginx_status_url,omitempty"`
	AccessLogPath   string                 `protobuf:"bytes,8,opt,name=access_log_path,json=accessLogPath,proto3" json:"access_log_path,omitempty"`
	ErrorLogPath    string                 `protobuf:"bytes,9,opt,name=error_log_path,json=errorLogPath,proto3" json:"error_log_path,omitempty"`
	LogFormat       string                 `protobuf:"bytes,10,opt,name=log_format,json=logFormat,proto3" json:"log_format,omitempty"`
	BufferDir       string                 `protobuf:"bytes,11,opt,name=buffer_dir,json=bufferDir,proto3" json:"buffer_dir,omitempty"`
	UpdateServer    string                 `protobuf:"bytes,12,opt,name=update_server,json=updateServer,proto3" json:"update_server,omitempty"`
	UpdateInterval  string                 `protobuf:"bytes,13,opt,name=update_interval,json=updateInterval,proto3" json:"update_interval,omitempty"`
	LogLevel        string                 `protobuf:"bytes,14,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogFile         string                 `protobuf:"bytes,15,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	ConfigFilePath  string                 `protobuf:"bytes,16,opt,name=config_file_path,json=configFilePath,proto3" json:"config_file_path,omitempty"` // Path to avika-agent.conf
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentConfigResponse) Reset() {
	*x = AgentConfigResponse{}
	mi := &file_api_proto_agent_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigResponse) ProtoMessage() {}

func (x *AgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigResponse.ProtoReflect.Descriptor instead.
func (*AgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_config_proto_rawDescGZIP(), []int{0}
}

func (x *AgentConfigResponse) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *AgentConfigResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentConfigResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentConfigResponse) GetHealthPort() int32 {
	if x != nil {
		return x.HealthPort
	}
	return 0
}

func (x *AgentConfigResponse) GetMgmtPort() int32 {
	if x != nil {
		return x.MgmtPort
	}
	return 0
}

func (x *AgentConfigResponse) GetNginxConfigPath() string {
	if x != nil {
		return x.NginxConfigPath
	}
	return ""
}

func (x *AgentConfigResponse) GetNginxStatusUrl() string {
	if x != nil {
		return x.NginxStatusUrl
	}
	return ""
}

func (x *AgentConfigResponse) GetAccessLogPath() string {
	if x != nil {
		return x.AccessLogPath
	}
	return ""
}

func (x *AgentConfigResponse) GetErrorLogPath() string {
	if x != nil {
		return x.ErrorLogPath
	}
	return ""
}

func (x *AgentConfigResponse) GetLogFormat() string {
	if x != nil {
		return x.LogFormat
	}
	return ""
}

func (x *AgentConfigResponse) GetBufferDir() string {
	if x != nil {
		return x.BufferDir
	}
	return ""
}

func (x *AgentConfigResponse) GetUpdateServer() string {
	if x != nil {
		return x.UpdateServer
	}
	return ""
}

func (x *AgentConfigResponse) GetUpdateInterval() string {
	if x != nil {
		return x.UpdateInterval
	}
	return ""
}

func (x *AgentConfigResponse) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *AgentConfigResponse) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *AgentConfigResponse) GetConfigFilePath() string {
	if x != nil {
		return x.ConfigFilePath
	}
	return ""
}

type AgentConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       map[string]string      `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key=value updates (config keys and LABEL_* supported)
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`                                                                          // Write to config file
	HotReload     bool                   `protobuf:"varint,3,opt,name=hot_reload,json=hotReload,proto3" json:"hot_reload,omitempty"`                                                     // Apply without restart where possible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigUpdate) Reset() {
	*x = AgentConfigUpdate{}
	mi := &file_api_proto_agent_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigUpdate) ProtoMessage() {}

func (x *AgentConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigUpdate.ProtoReflect.Descriptor instead.
func (*AgentConfigUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_config_proto_rawDescGZIP(), []int{1}
}

func (x *AgentConfigUpdate) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *AgentConfigUpdate) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *AgentConfigUpdate) GetHotReload() bool {
	if x != nil {
		return x.HotReload
	}
	return false
}

type AgentConfigUpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequiresRestart bool                   `protobuf:"varint,4,opt,name=requires_restart,json=requiresRestart,proto3" json:"requires_restart,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentConfigUpdateResponse) Reset() {
	*x = AgentConfigUpdateResponse{}
	mi := &file_api_proto_agent_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigUpdateResponse) ProtoMessage() {}

func (x *AgentConfigUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigUpdateResponse.ProtoReflect.Descriptor instead.
func (*AgentConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_config_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfigUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentConfigUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentConfigUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentConfigUpdateResponse) GetRequiresRestart() bool {
	if x != nil {
		return x.RequiresRestart
	}
	return false
}

type ConnectionTestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Supported types: "gateway", "nginx_status", "update_server"
	TestType string `protobuf:"bytes,1,opt,name=test_type,json=testType,proto3" json:"test_type,omitempty"`
	// Optional override endpoint URL/address to test.
	Endpoint      string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestRequest) Reset() {
	*x = ConnectionTestRequest{}
	mi := &file_api_proto_agent_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestRequest) ProtoMessage() {}

func (x *ConnectionTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestRequest.ProtoReflect.Descriptor instead.
func (*ConnectionTestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionTestRequest) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

func (x *ConnectionTestRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ConnectionTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestResponse) Reset() {
	*x = ConnectionTestResponse{}
	mi := &file_api_proto_agent_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestResponse) ProtoMessage() {}

func (x *ConnectionTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestResponse.ProtoReflect.Descriptor instead.
func (*ConnectionTestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionTestResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ConnectionTestResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_api_proto_agent_config_proto protoreflect.FileDescriptor

const file_api_proto_agent_config_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/agent_config.proto\x12\x0enginx.agent.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xad\x05\n" +
	"\x13AgentConfigResponse\x12'\n" +
	"\x0fgateway_address\x18\x01 \x01(\tR\x0egatewayAddress\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12G\n" +
	"\x06labels\x18\x03 \x03(\v2/.nginx.agent.v1.AgentConfigResponse.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vhealth_port\x18\x04 \x01(\x05R\n" +
	"healthPort\x12\x1b\n" +
	"\tmgmt_port\x18\x05 \x01(\x05R\bmgmtPort\x12*\n" +
	"\x11nginx_config_path\x18\x06 \x01(\tR\x0fnginxConfigPath\x12(\n" +
	"\x10nginx_status_url\x18\a \x01(\tR\x0enginxStatusUrl\x12&\n" +
	"\x0faccess_log_path\x18\b \x01(\tR\raccessLogPath\x12$\n" +
	"\x0eerror_log_path\x18\t \x01(\tR\ferrorLogPath\x12\x1d\n" +
	"\n" +
	"log_format\x18\n" +
	" \x01(\tR\tlogFormat\x12\x1d\n" +
	"\n" +
	"buffer_dir\x18\v \x01(\tR\tbufferDir\x12#\n" +
	"\rupdate_server\x18\f \x01(\tR\fupdateServer\x12'\n" +
	"\x0fupdate_interval\x18\r \x01(\tR\x0eupdateInterval\x12\x1b\n" +
	"\tlog_level\x18\x0e \x01(\tR\blogLevel\x12\x19\n" +
	"\blog_file\x18\x0f \x01(\tR\alogFile\x12(\n" +
	"\x10config_file_path\x18\x10 \x01(\tR\x0econfigFilePath\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x11AgentConfigUpdate\x12H\n" +
	"\aupdates\x18\x01 \x03(\v2..nginx.agent.v1.AgentConfigUpdate.UpdatesEntryR\aupdates\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\x12\x1d\n" +
	"\n" +
	"hot_reload\x18\x03 \x01(\bR\thotReload\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x19AgentConfigUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10requires_restart\x18\x04 \x01(\bR\x0frequiresRestart\"P\n" +
	"\x15ConnectionTestRequest\x12\x1b\n" +
	"\ttest_type\x18\x01 \x01(\tR\btestType\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"\xf6\x01\n" +
	"\x16ConnectionTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12M\n" +
	"\adetails\x18\x04 \x03(\v23.nginx.agent.v1.ConnectionTestResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa7\x02\n" +
	"\x12AgentConfigService\x12M\n" +
	"\x0eGetAgentConfig\x12\x16.google.protobuf.Empty\x1a#.nginx.agent.v1.AgentConfigResponse\x12a\n" +
	"\x11UpdateAgentConfig\x12!.nginx.agent.v1.AgentConfigUpdate\x1a).nginx.agent.v1.AgentConfigUpdateResponse\x12_\n" +
	"\x0eTestConnection\x12%.nginx.agent.v1.ConnectionTestRequest\x1a&.nginx.agent.v1.ConnectionTestResponseB7Z5github.com/avika-ai/avika/internal/common/proto/agentb\x06proto3"

var (
	file_api_proto_agent_config_proto_rawDescOnce sync.Once
	file_api_proto_agent_config_proto_rawDescData []byte
)

func file_api_proto_agent_config_proto_rawDescGZIP() []byte {
	file_api_proto_agent_config_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_config_proto_rawDesc), len(file_api_proto_agent_config_proto_rawDesc)))
	})
	return file_api_proto_agent_config_proto_rawDescData
}

var file_api_proto_agent_config_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_agent_config_proto_goTypes = []any{
	(*AgentConfigResponse)(nil),       // 0: nginx.agent.v1.AgentConfigResponse
	(*AgentConfigUpdate)(nil),         // 1: nginx.agent.v1.AgentConfigUpdate
	(*AgentConfigUpdateResponse)(nil), // 2: nginx.agent.v1.AgentConfigUpdateResponse
	(*ConnectionTestRequest)(nil),     // 3: nginx.agent.v1.ConnectionTestRequest
	(*ConnectionTestResponse)(nil),    // 4: nginx.agent.v1.ConnectionTestResponse
	nil,                               // 5: nginx.agent.v1.AgentConfigResponse.LabelsEntry
	nil,                               // 6: nginx.agent.v1.AgentConfigUpdate.UpdatesEntry
	nil,                               // 7: nginx.agent.v1.ConnectionTestResponse.DetailsEntry
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
}
var file_api_proto_agent_config_proto_depIdxs = []int32{
	5, // 0: nginx.agent.v1.AgentConfigResponse.labels:type_name -> nginx.agent.v1.AgentConfigResponse.LabelsEntry
	6, // 1: nginx.agent.v1.AgentConfigUpdate.updates:type_name -> nginx.agent.v1.AgentConfigUpdate.UpdatesEntry
	7, // 2: nginx.agent.v1.ConnectionTestResponse.details:type_name -> nginx.agent.v1.ConnectionTestResponse.DetailsEntry
	8, // 3: nginx.agent.v1.AgentConfigService.GetAgentConfig:input_type -> google.protobuf.Empty
	1, // 4: nginx.agent.v1.AgentConfigService.UpdateAgentConfig:input_type -> nginx.agent.v1.AgentConfigUpdate
	3, // 5: nginx.agent.v1.AgentConfigService.TestConnection:input_type -> nginx.agent.v1.ConnectionTestRequest
	0, // 6: nginx.agent.v1.AgentConfigService.GetAgentConfig:output_type -> nginx.agent.v1.AgentConfigResponse
	2, // 7: nginx.agent.v1.AgentConfigService.UpdateAgentConfig:output_type -> nginx.agent.v1.AgentConfigUpdateResponse
	4, // 8: nginx.agent.v1.AgentConfigService.TestConnection:output_type -> nginx.agent.v1.ConnectionTestResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_agent_config_proto_init() }
func file_api_proto_agent_config_proto_init() {
	if File_api_proto_agent_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_config_proto_rawDesc), len(file_api_proto_agent_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_config_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_config_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_config_proto_msgTypes,
	}.Build()
	File_api_proto_agent_config_proto = out.File
	file_api_proto_agent_config_proto_goTypes = nil
	file_api_proto_agent_config_proto_depIdxs = nil
}
