// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent_config.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentConfigResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GatewayAddress  string                 `protobuf:"bytes,1,opt,name=gateway_address,json=gatewayAddress,proto3" json:"gateway_address,omitempty"`
	AgentId         string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HealthPort      int32                  `protobuf:"varint,4,opt,name=health_port,json=healthPort,proto3" json:"health_port,omitempty"`
	MgmtPort        int32                  `protobuf:"varint,5,opt,name=mgmt_port,json=mgmtPort,proto3" json:"mgmt_port,omitempty"`
	NginxConfigPath string                 `protobuf:"bytes,6,opt,name=nginx_config_path,json=nginxConfigPath,proto3" json:"nginx_config_path,omitempty"`
	NginxStatusUrl  string                 `protobuf:"bytes,7,opt,name=nginx_status_url,json=nginxStatusUrl,proto3" json:"nginx_status_url,omitempty"`
	AccessLogPath   string                 `protobuf:"bytes,8,opt,name=access_log_path,json=accessLogPath,proto3" json:"access_log_path,omitempty"`
	ErrorLogPath    string                 `protobuf:"bytes,9,opt,name=error_log_path,json=errorLogPath,proto3" json:"error_log_path,omitempty"`
	LogFormat       string                 `protobuf:"bytes,10,opt,name=log_format,json=logFormat,proto3" json:"log_format,omitempty"`
	BufferDir       string                 `protobuf:"bytes,11,opt,name=buffer_dir,json=bufferDir,proto3" json:"buffer_dir,omitempty"`
	UpdateServer    string                 `protobuf:"bytes,12,opt,name=update_server,json=updateServer,proto3" json:"update_server,omitempty"`
	UpdateInterval  string                 `protobuf:"bytes,13,opt,name=update_interval,json=updateInterval,proto3" json:"update_interval,omitempty"`
	LogLevel        string                 `protobuf:"bytes,14,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogFile         string                 `protobuf:"bytes,15,opt,name=log_file,json=logFile,proto3" json:"log_file,omitempty"`
	ConfigFilePath  string                 `protobuf:"bytes,16,opt,name=config_file_path,json=configFilePath,proto3" json:"config_file_path,omitempty"` // Path to avika-agent.conf
	MgmtAdvertise   string                 `protobuf:"bytes,17,opt,name=mgmt_advertise,json=mgmtAdvertise,proto3" json:"mgmt_advertise,omitempty"`      // AVIKA_MGMT_ADVERTISE: IP or host:port for gateway dial-back
	MgmtNatCidr     string                 `protobuf:"bytes,18,opt,name=mgmt_nat_cidr,json=mgmtNatCidr,proto3" json:"mgmt_nat_cidr,omitempty"`          // AVIKA_MGMT_NAT_CIDR: CIDR to avoid when choosing mgmt IP (e.g. 10.0.2.0/24)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAgentConfigResponse) Reset() {
	*x = GetAgentConfigResponse{}
	mi := &file_agent_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentConfigResponse) ProtoMessage() {}

func (x *GetAgentConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAgentConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetAgentConfigResponse) GetGatewayAddress() string {
	if x != nil {
		return x.GatewayAddress
	}
	return ""
}

func (x *GetAgentConfigResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetAgentConfigResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GetAgentConfigResponse) GetHealthPort() int32 {
	if x != nil {
		return x.HealthPort
	}
	return 0
}

func (x *GetAgentConfigResponse) GetMgmtPort() int32 {
	if x != nil {
		return x.MgmtPort
	}
	return 0
}

func (x *GetAgentConfigResponse) GetNginxConfigPath() string {
	if x != nil {
		return x.NginxConfigPath
	}
	return ""
}

func (x *GetAgentConfigResponse) GetNginxStatusUrl() string {
	if x != nil {
		return x.NginxStatusUrl
	}
	return ""
}

func (x *GetAgentConfigResponse) GetAccessLogPath() string {
	if x != nil {
		return x.AccessLogPath
	}
	return ""
}

func (x *GetAgentConfigResponse) GetErrorLogPath() string {
	if x != nil {
		return x.ErrorLogPath
	}
	return ""
}

func (x *GetAgentConfigResponse) GetLogFormat() string {
	if x != nil {
		return x.LogFormat
	}
	return ""
}

func (x *GetAgentConfigResponse) GetBufferDir() string {
	if x != nil {
		return x.BufferDir
	}
	return ""
}

func (x *GetAgentConfigResponse) GetUpdateServer() string {
	if x != nil {
		return x.UpdateServer
	}
	return ""
}

func (x *GetAgentConfigResponse) GetUpdateInterval() string {
	if x != nil {
		return x.UpdateInterval
	}
	return ""
}

func (x *GetAgentConfigResponse) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *GetAgentConfigResponse) GetLogFile() string {
	if x != nil {
		return x.LogFile
	}
	return ""
}

func (x *GetAgentConfigResponse) GetConfigFilePath() string {
	if x != nil {
		return x.ConfigFilePath
	}
	return ""
}

func (x *GetAgentConfigResponse) GetMgmtAdvertise() string {
	if x != nil {
		return x.MgmtAdvertise
	}
	return ""
}

func (x *GetAgentConfigResponse) GetMgmtNatCidr() string {
	if x != nil {
		return x.MgmtNatCidr
	}
	return ""
}

type AgentConfigUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updates       map[string]string      `protobuf:"bytes,1,rep,name=updates,proto3" json:"updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key=value updates (config keys and LABEL_* supported)
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`                                                                          // Write to config file
	HotReload     bool                   `protobuf:"varint,3,opt,name=hot_reload,json=hotReload,proto3" json:"hot_reload,omitempty"`                                                     // Apply without restart where possible
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentConfigUpdate) Reset() {
	*x = AgentConfigUpdate{}
	mi := &file_agent_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigUpdate) ProtoMessage() {}

func (x *AgentConfigUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigUpdate.ProtoReflect.Descriptor instead.
func (*AgentConfigUpdate) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{1}
}

func (x *AgentConfigUpdate) GetUpdates() map[string]string {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *AgentConfigUpdate) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *AgentConfigUpdate) GetHotReload() bool {
	if x != nil {
		return x.HotReload
	}
	return false
}

type AgentConfigUpdateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RequiresRestart bool                   `protobuf:"varint,4,opt,name=requires_restart,json=requiresRestart,proto3" json:"requires_restart,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentConfigUpdateResponse) Reset() {
	*x = AgentConfigUpdateResponse{}
	mi := &file_agent_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfigUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfigUpdateResponse) ProtoMessage() {}

func (x *AgentConfigUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfigUpdateResponse.ProtoReflect.Descriptor instead.
func (*AgentConfigUpdateResponse) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{2}
}

func (x *AgentConfigUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AgentConfigUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentConfigUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentConfigUpdateResponse) GetRequiresRestart() bool {
	if x != nil {
		return x.RequiresRestart
	}
	return false
}

type ConnectionTestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Supported types: "gateway", "nginx_status", "update_server"
	TestType string `protobuf:"bytes,1,opt,name=test_type,json=testType,proto3" json:"test_type,omitempty"`
	// Optional override endpoint URL/address to test.
	Endpoint      string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestRequest) Reset() {
	*x = ConnectionTestRequest{}
	mi := &file_agent_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestRequest) ProtoMessage() {}

func (x *ConnectionTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestRequest.ProtoReflect.Descriptor instead.
func (*ConnectionTestRequest) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionTestRequest) GetTestType() string {
	if x != nil {
		return x.TestType
	}
	return ""
}

func (x *ConnectionTestRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type ConnectionTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Details       map[string]string      `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionTestResponse) Reset() {
	*x = ConnectionTestResponse{}
	mi := &file_agent_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionTestResponse) ProtoMessage() {}

func (x *ConnectionTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionTestResponse.ProtoReflect.Descriptor instead.
func (*ConnectionTestResponse) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConnectionTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConnectionTestResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ConnectionTestResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ListConfigBackupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backups       []*ConfigBackupEntry   `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConfigBackupsResponse) Reset() {
	*x = ListConfigBackupsResponse{}
	mi := &file_agent_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConfigBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConfigBackupsResponse) ProtoMessage() {}

func (x *ListConfigBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConfigBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListConfigBackupsResponse) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{5}
}

func (x *ListConfigBackupsResponse) GetBackups() []*ConfigBackupEntry {
	if x != nil {
		return x.Backups
	}
	return nil
}

type ConfigBackupEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // filename (e.g. avika-agent.conf.20060102T150405Z.bak)
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigBackupEntry) Reset() {
	*x = ConfigBackupEntry{}
	mi := &file_agent_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigBackupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigBackupEntry) ProtoMessage() {}

func (x *ConfigBackupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigBackupEntry.ProtoReflect.Descriptor instead.
func (*ConfigBackupEntry) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigBackupEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigBackupEntry) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type RestoreConfigBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupName    string                 `protobuf:"bytes,1,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"` // filename from ListConfigBackups
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreConfigBackupRequest) Reset() {
	*x = RestoreConfigBackupRequest{}
	mi := &file_agent_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreConfigBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreConfigBackupRequest) ProtoMessage() {}

func (x *RestoreConfigBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreConfigBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreConfigBackupRequest) Descriptor() ([]byte, []int) {
	return file_agent_config_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreConfigBackupRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

var File_agent_config_proto protoreflect.FileDescriptor

const file_agent_config_proto_rawDesc = "" +
	"\n" +
	"\x12agent_config.proto\x12\x0enginx.agent.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xfe\x05\n" +
	"\x16GetAgentConfigResponse\x12'\n" +
	"\x0fgateway_address\x18\x01 \x01(\tR\x0egatewayAddress\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.nginx.agent.v1.GetAgentConfigResponse.LabelsEntryR\x06labels\x12\x1f\n" +
	"\vhealth_port\x18\x04 \x01(\x05R\n" +
	"healthPort\x12\x1b\n" +
	"\tmgmt_port\x18\x05 \x01(\x05R\bmgmtPort\x12*\n" +
	"\x11nginx_config_path\x18\x06 \x01(\tR\x0fnginxConfigPath\x12(\n" +
	"\x10nginx_status_url\x18\a \x01(\tR\x0enginxStatusUrl\x12&\n" +
	"\x0faccess_log_path\x18\b \x01(\tR\raccessLogPath\x12$\n" +
	"\x0eerror_log_path\x18\t \x01(\tR\ferrorLogPath\x12\x1d\n" +
	"\n" +
	"log_format\x18\n" +
	" \x01(\tR\tlogFormat\x12\x1d\n" +
	"\n" +
	"buffer_dir\x18\v \x01(\tR\tbufferDir\x12#\n" +
	"\rupdate_server\x18\f \x01(\tR\fupdateServer\x12'\n" +
	"\x0fupdate_interval\x18\r \x01(\tR\x0eupdateInterval\x12\x1b\n" +
	"\tlog_level\x18\x0e \x01(\tR\blogLevel\x12\x19\n" +
	"\blog_file\x18\x0f \x01(\tR\alogFile\x12(\n" +
	"\x10config_file_path\x18\x10 \x01(\tR\x0econfigFilePath\x12%\n" +
	"\x0emgmt_advertise\x18\x11 \x01(\tR\rmgmtAdvertise\x12\"\n" +
	"\rmgmt_nat_cidr\x18\x12 \x01(\tR\vmgmtNatCidr\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x11AgentConfigUpdate\x12H\n" +
	"\aupdates\x18\x01 \x03(\v2..nginx.agent.v1.AgentConfigUpdate.UpdatesEntryR\aupdates\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\x12\x1d\n" +
	"\n" +
	"hot_reload\x18\x03 \x01(\bR\thotReload\x1a:\n" +
	"\fUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x19AgentConfigUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12)\n" +
	"\x10requires_restart\x18\x04 \x01(\bR\x0frequiresRestart\"P\n" +
	"\x15ConnectionTestRequest\x12\x1b\n" +
	"\ttest_type\x18\x01 \x01(\tR\btestType\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\"\xf6\x01\n" +
	"\x16ConnectionTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12M\n" +
	"\adetails\x18\x04 \x03(\v23.nginx.agent.v1.ConnectionTestResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"X\n" +
	"\x19ListConfigBackupsResponse\x12;\n" +
	"\abackups\x18\x01 \x03(\v2!.nginx.agent.v1.ConfigBackupEntryR\abackups\"F\n" +
	"\x11ConfigBackupEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\"=\n" +
	"\x1aRestoreConfigBackupRequest\x12\x1f\n" +
	"\vbackup_name\x18\x01 \x01(\tR\n" +
	"backupName2\xf0\x03\n" +
	"\x12AgentConfigService\x12P\n" +
	"\x0eGetAgentConfig\x12\x16.google.protobuf.Empty\x1a&.nginx.agent.v1.GetAgentConfigResponse\x12a\n" +
	"\x11UpdateAgentConfig\x12!.nginx.agent.v1.AgentConfigUpdate\x1a).nginx.agent.v1.AgentConfigUpdateResponse\x12_\n" +
	"\x0eTestConnection\x12%.nginx.agent.v1.ConnectionTestRequest\x1a&.nginx.agent.v1.ConnectionTestResponse\x12V\n" +
	"\x11ListConfigBackups\x12\x16.google.protobuf.Empty\x1a).nginx.agent.v1.ListConfigBackupsResponse\x12l\n" +
	"\x13RestoreConfigBackup\x12*.nginx.agent.v1.RestoreConfigBackupRequest\x1a).nginx.agent.v1.AgentConfigUpdateResponseB7Z5github.com/avika-ai/avika/internal/common/proto/agentb\x06proto3"

var (
	file_agent_config_proto_rawDescOnce sync.Once
	file_agent_config_proto_rawDescData []byte
)

func file_agent_config_proto_rawDescGZIP() []byte {
	file_agent_config_proto_rawDescOnce.Do(func() {
		file_agent_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_config_proto_rawDesc), len(file_agent_config_proto_rawDesc)))
	})
	return file_agent_config_proto_rawDescData
}

var file_agent_config_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_config_proto_goTypes = []any{
	(*GetAgentConfigResponse)(nil),     // 0: nginx.agent.v1.GetAgentConfigResponse
	(*AgentConfigUpdate)(nil),          // 1: nginx.agent.v1.AgentConfigUpdate
	(*AgentConfigUpdateResponse)(nil),  // 2: nginx.agent.v1.AgentConfigUpdateResponse
	(*ConnectionTestRequest)(nil),      // 3: nginx.agent.v1.ConnectionTestRequest
	(*ConnectionTestResponse)(nil),     // 4: nginx.agent.v1.ConnectionTestResponse
	(*ListConfigBackupsResponse)(nil),  // 5: nginx.agent.v1.ListConfigBackupsResponse
	(*ConfigBackupEntry)(nil),          // 6: nginx.agent.v1.ConfigBackupEntry
	(*RestoreConfigBackupRequest)(nil), // 7: nginx.agent.v1.RestoreConfigBackupRequest
	nil,                                // 8: nginx.agent.v1.GetAgentConfigResponse.LabelsEntry
	nil,                                // 9: nginx.agent.v1.AgentConfigUpdate.UpdatesEntry
	nil,                                // 10: nginx.agent.v1.ConnectionTestResponse.DetailsEntry
	(*emptypb.Empty)(nil),              // 11: google.protobuf.Empty
}
var file_agent_config_proto_depIdxs = []int32{
	8,  // 0: nginx.agent.v1.GetAgentConfigResponse.labels:type_name -> nginx.agent.v1.GetAgentConfigResponse.LabelsEntry
	9,  // 1: nginx.agent.v1.AgentConfigUpdate.updates:type_name -> nginx.agent.v1.AgentConfigUpdate.UpdatesEntry
	10, // 2: nginx.agent.v1.ConnectionTestResponse.details:type_name -> nginx.agent.v1.ConnectionTestResponse.DetailsEntry
	6,  // 3: nginx.agent.v1.ListConfigBackupsResponse.backups:type_name -> nginx.agent.v1.ConfigBackupEntry
	11, // 4: nginx.agent.v1.AgentConfigService.GetAgentConfig:input_type -> google.protobuf.Empty
	1,  // 5: nginx.agent.v1.AgentConfigService.UpdateAgentConfig:input_type -> nginx.agent.v1.AgentConfigUpdate
	3,  // 6: nginx.agent.v1.AgentConfigService.TestConnection:input_type -> nginx.agent.v1.ConnectionTestRequest
	11, // 7: nginx.agent.v1.AgentConfigService.ListConfigBackups:input_type -> google.protobuf.Empty
	7,  // 8: nginx.agent.v1.AgentConfigService.RestoreConfigBackup:input_type -> nginx.agent.v1.RestoreConfigBackupRequest
	0,  // 9: nginx.agent.v1.AgentConfigService.GetAgentConfig:output_type -> nginx.agent.v1.GetAgentConfigResponse
	2,  // 10: nginx.agent.v1.AgentConfigService.UpdateAgentConfig:output_type -> nginx.agent.v1.AgentConfigUpdateResponse
	4,  // 11: nginx.agent.v1.AgentConfigService.TestConnection:output_type -> nginx.agent.v1.ConnectionTestResponse
	5,  // 12: nginx.agent.v1.AgentConfigService.ListConfigBackups:output_type -> nginx.agent.v1.ListConfigBackupsResponse
	2,  // 13: nginx.agent.v1.AgentConfigService.RestoreConfigBackup:output_type -> nginx.agent.v1.AgentConfigUpdateResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_config_proto_init() }
func file_agent_config_proto_init() {
	if File_agent_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_config_proto_rawDesc), len(file_agent_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_config_proto_goTypes,
		DependencyIndexes: file_agent_config_proto_depIdxs,
		MessageInfos:      file_agent_config_proto_msgTypes,
	}.Build()
	File_agent_config_proto = out.File
	file_agent_config_proto_goTypes = nil
	file_agent_config_proto_depIdxs = nil
}
