{{- if or .Values.nginx.enabled .Values.haproxy.enabled }}
{{- $cert := genSelfSignedCert "ncn112.com" nil (list "ncn112.com" "www.ncn112.com") 3650 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "avika.fullname" . }}-nginx-tls
  labels:
    {{- include "avika.labels" . | nindent 4 }}
    component: nginx
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
