export function generateProvisionSnippet(template: string, config: Record<string, any>): string {
    const header = "# Generated by Avika Provisioner\n";

    switch (template) {
        case 'rate-limiting':
            const rpm = config.requests_per_minute || 60;
            const burst = config.burst_size || 20;
            return `${header}limit_req_zone $binary_remote_addr zone=api_limit:10m rate=${rpm}r/m;\n\nserver {\n    location /api/ {\n        limit_req zone=api_limit burst=${burst} nodelay;\n        proxy_pass http://backend;\n    }\n}`;

        case 'health-checks':
            return `${header}upstream ${config.upstream_name || 'backend'} {\n${config.servers || '    server 127.0.0.1:8080;'}\n    \n    # NOTE: 'check' directive requires nginx_upstream_check_module or NGINX Plus\n    check interval=${config.interval || 3000} rise=${config.rise || 2} fall=${config.fall || 3} timeout=${config.timeout || 1000};\n}`;

        case 'location-blocks':
            return `${header}location ${config.path || '/'} {\n${config.directives || '    # Add directives here'}\n}`;

        case 'error-pages':
            return `${header}error_page ${config.error_codes || '404 500 502'} ${config.page_path || '/error.html'};\n\nlocation = ${config.page_path || '/error.html'} {\n    root /usr/share/nginx/html;\n    internal;\n}`;

        case 'custom':
            return `${header}${config.raw_config || '# No config provided'}`;

        default:
            return "# Unknown template";
    }
}
